# Generated by Django 4.2 on 2024-05-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_alter_artifact_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artifact',
            table='artifacts2',
        ),
    ]
